# Aliases
alias ll='ls -alF'
alias ~='cd ~'
alias grep='grep --color=auto --exclude-dir={.bzr,.cvs,.git,.hg,.svn}'

# Git aliases
alias g=git
alias ga='git add'
alias gaa='git add --all'
alias gac='git add . && git commit -v'
alias gapa='git add --patch'
alias gb='git branch'
alias gc='git commit -v'
alias gca='git commit -v -a'
alias gcb='git checkout -b'
alias gcl='git clone --recursive'
alias gclean='git reset --hard && git clean -dfx'
alias gcmsg='git commit -m'
alias gco='git checkout'
alias gcp='git cherry-pick'
alias gd='git diff'
alias gdca='git diff --cached'
alias gf='git fetch'
alias gfa='git fetch --all --prune'
alias gfo='git fetch origin'
alias gl='git pull'
alias glo='git pull origin'
alias gup='git pull --rebase'
alias glg='git log --stat --color'
alias glog='git log --oneline --decorate --color'
alias glogg='git log --oneline --decorate --color --graph'
alias gm='git merge'
alias gp='git push'
alias gpo='git push origin'
alias gr='git remote'
alias grb='git rebase'
alias grba='git rebase --abort'
alias grbc='git rebase --continue'
alias grbi='git rebase -i'
alias grbs='git rebase --skip'
alias grh='git reset HEAD'
alias grhh='git reset HEAD --hard'
alias grt='cd $(git rev-parse --show-toplevel || echo ".")'
alias grv='git remote -v'
alias gsb='git status -sb'
alias gst='git status'
alias gsta='git stash'
alias gstaa='git stash apply'
alias gstd='git stash drop'
alias gstl='git stash list'
alias gstp='git stash pop'
alias gsts='git stash show --text'

# Git worktree aliases
alias gwt='git worktree'
alias gwta='git worktree add'
alias gwtl='git worktree list'
alias gwtr='git worktree remove'
alias gwtp='git worktree prune'
alias gwtm='git worktree move'
alias gwtlk='git worktree lock'
alias gwtul='git worktree unlock'

# GitHub CLI aliases
alias ghb='gh browse'
alias ghs='gh status'

# GitHub CLI PRs aliases
alias gpr='gh pr'
alias gprc='gh pr create'
alias gprcf='gh pr create --fill'
alias gprl='gh pr list'
alias gprv='gh pr view'
alias gprvw='gh pr view --web'
alias gprco='gh pr checkout'
alias gprs='gh pr status'
alias gprch='gh pr checks'
alias gprd='gh pr diff'
alias gprm='gh pr merge'
alias gprr='gh pr ready'
alias gprrv='gh pr review'

# GitHub CLI issues aliases
alias gis='gh issue'
alias gisc='gh issue create'
alias gisl='gh issue list'
alias gisv='gh issue view'
alias gisvw='gh issue view --web'

# GitHub CLI repo / actions aliases
alias grepo='gh repo'
alias grepov='gh repo view'
alias grepovw='gh repo view --web'
alias grcl='gh repo clone'
alias grrun='gh run'
alias grrunl='gh run list'
alias grrunv='gh run view'
alias grrunw='gh run watch'

# GitHub CLI stack aliases (also: `gs` wrapper via `gh stack alias` → ~/.local/bin/gs)
alias gsi='gh stack init'
alias gsa='gh stack add'
alias gssub='gh stack submit'
alias gssync='gh stack sync'
alias gsv='gh stack view'
alias gsp='gh stack push'
alias gsm='gh stack merge'
alias gsreb='gh stack rebase'
alias gsmod='gh stack modify'
alias gsco='gh stack checkout'
alias gsup='gh stack up'
alias gsdown='gh stack down'
alias gstop='gh stack top'
alias gsbottom='gh stack bottom'
alias gstrunk='gh stack trunk'
alias gssw='gh stack switch'
alias gsun='gh stack unstack'

# Autojump
[ -f /opt/homebrew/etc/profile.d/autojump.sh ] && . /opt/homebrew/etc/profile.d/autojump.sh

# Python
export OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES

# Ruby
eval "$(rbenv init -)"
export RUBY_CONFIGURE_OPTS="--with-openssl-dir=$(brew --prefix openssl)"

# Node
export NVM_DIR="$HOME/.nvm"
# this loads nvm
[ -s "/opt/homebrew/opt/nvm/nvm.sh" ] && . "/opt/homebrew/opt/nvm/nvm.sh"
# this loads nvm bash_completion
[ -s "/opt/homebrew/opt/nvm/etc/bash_completion.d/nvm" ] && . "/opt/homebrew/opt/nvm/etc/bash_completion.d/nvm"
# place this after nvm initialization!
autoload -U add-zsh-hook
load_nvmrc() {
  local node_version="$(nvm version)"
  local nvmrc_path="$(nvm_find_nvmrc)"

  if [ -n "$nvmrc_path" ]; then
    local nvmrc_node_version=$(nvm version "$(cat "${nvmrc_path}")")

    if [ "$nvmrc_node_version" != "N/A" ] && [ "$nvmrc_node_version" != "$node_version" ]; then
      nvm use
    fi
  elif [ "$node_version" != "$(nvm version default)" ]; then
    echo "Reverting to nvm default version"
    nvm use default
  fi
}
add-zsh-hook chpwd load_nvmrc
load_nvmrc

# Docker CLI completions
fpath=($HOME/.docker/completions $fpath)
autoload -Uz compinit
compinit

# LM Studio CLI
export PATH="$PATH:$HOME/.lmstudio/bin"

export PATH="$HOME/.local/bin:$PATH"
